bastion_home_dir: "/home/{{ ansible_ssh_user }}"



# cluster namings 
base_domain: 
cluster_name: 
cluster_domain_name: "{{ cluster_name }}.{{ base_domain }}"

# Red Hat subscription credentials for bsation RHEL8
redhat_subscription_username: 
redhat_subscription_password: 

# bastion configuration
ocp4_bastion_flavor: "m1.small"
ansible_ssh_private_key_file: 
bastion_image_name: #glange image name for a RHEL8 image


# OCP4 installer info
ocp4_installer_url: "https://mirror.openshift.com/pub/openshift-v4/clients/ocp/4.3.13/openshift-install-linux-4.3.13.tar.gz"
ocp4_pull_secret: "{{ lookup('file', '~/.ocp4_pull_secret') | from_json }}"
ocp4_dir: "{{ bastion_home_dir }}/ocp-install"
ocp4_install_dir:
# OSP4 fields for install-config
local_os_cacert: # i.e. /home/mali/.config/openstack/controller14.v2v.bos.redhat.com-ca.pem
computer_flavor: 
external_network: 
existing_image_name: 
external_dns_ips:
- #dns server1
- #dns server2 . etc

# OSP credentials
os_cloud: 
os_auth_url: 
os_username: 
os_password: 
os_project_id: 
os_project_name: 
os_cacert: 
os_user_domain_name: 
os_region_name:
os_interface: 
os_identity_api_version: 

