---
# tasks file for detroy-cluster
- name: Delete floating ips
  shell: openstack floating ip delete --os-cloud={{ os_cloud }} $(openstack floating ip list --os-cloud={{ os_cloud }} --tags "{{ cluster_name }}" -f value -c "ID")
  check_mode: yes

- name: Detroy ocp4 cluster
  shell: ./openshift-install destroy cluster --dir={{ ocp4_install_dir }}
  args: 
    chdir: "{{ ocp4_dir }}" 
