---
# tasks file for configure-osp

- name: create /etc/openstack
  file:
    path: /etc/openstack
    state: directory
  become: true

- name: copy over OpenStack ca
  copy:
    src: "{{ local_os_cacert }}"
    dest: "{{ os_cacert }}"
  become: true

- name: add ca to ca-trust
  shell: update-ca-trust extract
  become: true 

- name: create clouds.yaml
  template:
    src: clouds.yaml.j2
    dest: /etc/openstack/clouds.yaml
  become: true

